# Generated by Django 6.1 on 2026-08-27 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_menu_inventory_menu_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Reservation',
        ),
        migrations.RenameModel(
            old_name='UserComments',
            new_name='Reviews',
        ),
    ]
